# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-16 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=11, unique=True, verbose_name='用户名'),
        ),
    ]
