# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-17 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200417_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_avtive',
            new_name='is_active',
        ),
    ]
